cask_args appdir: '/Applications'

brew 'neovim'
brew 'tmux'
brew 'tmate'
brew 'the_silver_searcher'
brew 'bat'
brew 'htop'
brew 'git-crypt'
brew 'universal-ctags'
brew 'shellcheck'
brew 'jq'
brew 'lazydocker'
brew 'k9s'
brew 'openjdk'
brew 'steampipe'

cask 'font-hack-nerd-font'
cask 'font-fira-code'
